/* Generated By:JavaCC: Do not edit this line. GrammarTreeConstants.java Version 5.0 */
public interface GrammarTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTVOID = 1;
  public int JJTSIMPLESTMT = 2;
  public int JJTEXPRSTMT = 3;
  public int JJTANNASSIGN = 4;
  public int JJTTESTLISTSTAREXPR = 5;
  public int JJTAUGASSIGN = 6;
  public int JJTFLOWSTMT = 7;
  public int JJTBREAKSTMT = 8;
  public int JJTCONTINUESTMT = 9;
  public int JJTRETURNSTMT = 10;
  public int JJTYIELDSTMT = 11;
  public int JJTYIELDEXPR = 12;
  public int JJTYIELDARG = 13;
  public int JJTRAISESTMT = 14;
  public int JJTIMPORTSTMT = 15;
  public int JJTIMPORTNAME = 16;
  public int JJTIMPORTFROM = 17;
  public int JJTIMPORTASNAME = 18;
  public int JJTDOTTEDASNAME = 19;
  public int JJTIMPORTASNAMES = 20;
  public int JJTDOTTEDASNAMES = 21;
  public int JJTDOTTEDNAME = 22;
  public int JJTASSERTSTMT = 23;
  public int JJTCOMPOUNDSTMT = 24;
  public int JJTIFSTMT = 25;
  public int JJTWHILESTMT = 26;
  public int JJTDOSTMT = 27;
  public int JJTFORSTMT = 28;
  public int JJTTRYSTMT = 29;
  public int JJTHANDLECLAUSE = 30;
  public int JJTSUITE = 31;
  public int JJTWITHSTMT = 32;
  public int JJTWITHITEM = 33;
  public int JJTTEST = 34;
  public int JJTORTEST = 35;
  public int JJTXORTEST = 36;
  public int JJTANDTEST = 37;
  public int JJTNOTTEST = 38;
  public int JJTCOMPARISON = 39;
  public int JJTCOMPOP = 40;
  public int JJTEXPR = 41;
  public int JJTXOREXPR = 42;
  public int JJTANDEXPR = 43;
  public int JJTSHIFTEXPR = 44;
  public int JJTSHIFTLEFT = 45;
  public int JJTSHIFTRIGHT = 46;
  public int JJTARITHEXPR = 47;
  public int JJTPLUS = 48;
  public int JJTMINUS = 49;
  public int JJTTERM = 50;
  public int JJTMULTIPLY = 51;
  public int JJTDIVIDE = 52;
  public int JJTMOD = 53;
  public int JJTDIVIDEINT = 54;
  public int JJTFACTOR = 55;
  public int JJTTILDE = 56;
  public int JJTPOWER = 57;
  public int JJTATOMEXPR = 58;
  public int JJTATOM = 59;
  public int JJTNAME = 60;
  public int JJTNUMBER = 61;
  public int JJTTRUE = 62;
  public int JJTFALSE = 63;
  public int JJTARGS = 64;
  public int JJTSTRING = 65;
  public int JJTTESTLISTCOMP = 66;
  public int JJTTRAILER = 67;
  public int JJTSUBSCRIPTLIST = 68;
  public int JJTSUBSCRIPT = 69;
  public int JJTARGLIST = 70;
  public int JJTARGUMENT = 71;
  public int JJTCOMPITER = 72;
  public int JJTCOMPFOR = 73;
  public int JJTCOMPIF = 74;
  public int JJTSLICEOP = 75;
  public int JJTEXPRLIST = 76;
  public int JJTSTAREXPR = 77;
  public int JJTTESTLIST = 78;
  public int JJTFUNCDEF = 79;
  public int JJTCLASSDEF = 80;
  public int JJTMODIFIER = 81;
  public int JJTCLASSNAME = 82;
  public int JJTINTERFACENAME = 83;
  public int JJTCLASSSUITE = 84;
  public int JJTCLASSSTMT = 85;
  public int JJTMETHODDEF = 86;
  public int JJTCONSTRUCTORDEF = 87;
  public int JJTVARDEF = 88;
  public int JJTINTERFACEDEF = 89;
  public int JJTPARAMETERS = 90;
  public int JJTTYPEDARGLIST = 91;
  public int JJTTFPDEF = 92;
  public int JJTLAMBDEF = 93;
  public int JJTLAMBDEFNOCOND = 94;
  public int JJTVARARGLIST = 95;
  public int JJTTESTNOCOND = 96;
  public int JJTERROR_PRINTMESSAGE = 97;


  public String[] jjtNodeName = {
    "Input",
    "void",
    "SimpleStmt",
    "ExprStmt",
    "Annassign",
    "TestlistStarExpr",
    "Augassign",
    "FlowStmt",
    "BreakStmt",
    "ContinueStmt",
    "ReturnStmt",
    "YieldStmt",
    "YieldExpr",
    "YieldArg",
    "RaiseStmt",
    "ImportStmt",
    "ImportName",
    "ImportFrom",
    "ImportAsName",
    "DottedAsName",
    "ImportAsNames",
    "DottedAsNames",
    "DottedName",
    "AssertStmt",
    "CompoundStmt",
    "IfStmt",
    "WhileStmt",
    "DoStmt",
    "ForStmt",
    "TryStmt",
    "HandleClause",
    "Suite",
    "WithStmt",
    "WithItem",
    "Test",
    "OrTest",
    "XorTest",
    "AndTest",
    "NotTest",
    "Comparison",
    "CompOp",
    "Expr",
    "XorExpr",
    "AndExpr",
    "ShiftExpr",
    "ShiftLeft",
    "ShiftRight",
    "ArithExpr",
    "Plus",
    "Minus",
    "Term",
    "Multiply",
    "Divide",
    "Mod",
    "DivideInt",
    "Factor",
    "Tilde",
    "Power",
    "AtomExpr",
    "Atom",
    "Name",
    "Number",
    "True",
    "False",
    "Args",
    "String",
    "TestlistComp",
    "Trailer",
    "Subscriptlist",
    "Subscript",
    "Arglist",
    "Argument",
    "CompIter",
    "CompFor",
    "CompIf",
    "SliceOp",
    "Exprlist",
    "StarExpr",
    "Testlist",
    "FuncDef",
    "ClassDef",
    "Modifier",
    "ClassName",
    "InterfaceName",
    "ClassSuite",
    "ClassStmt",
    "MethodDef",
    "ConstructorDef",
    "VarDef",
    "InterfaceDef",
    "Parameters",
    "TypeDArglist",
    "TfpDef",
    "LambDef",
    "LambDefNocond",
    "VarArglist",
    "TestNocond",
    "error_printmessage",
  };
}
/* JavaCC - OriginalChecksum=1d31ae9f8f21863e4ff7f3b3e02b5dd0 (do not edit this line) */
