/* Generated By:JavaCC: Do not edit this line. GrammarTreeConstants.java Version 5.0 */
public interface GrammarTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTVOID = 1;
  public int JJTSIMPLESTMT = 2;
  public int JJTEXPRSTMT = 3;
  public int JJTANNASSIGN = 4;
  public int JJTTESTLISTSTAREXPR = 5;
  public int JJTAUGASSIGN = 6;
  public int JJTFLOWSTMT = 7;
  public int JJTBREAKSTMT = 8;
  public int JJTCONTINUESTMT = 9;
  public int JJTRETURNSTMT = 10;
  public int JJTYIELDSTMT = 11;
  public int JJTYIELDEXPR = 12;
  public int JJTYIELDARG = 13;
  public int JJTRAISESTMT = 14;
  public int JJTIMPORTSTMT = 15;
  public int JJTIMPORTNAME = 16;
  public int JJTIMPORTFROM = 17;
  public int JJTIMPORTASNAME = 18;
  public int JJTDOTTEDASNAME = 19;
  public int JJTIMPORTASNAMES = 20;
  public int JJTDOTTEDASNAMES = 21;
  public int JJTDOTTEDNAME = 22;
  public int JJTASSERTSTMT = 23;
  public int JJTCOMPOUNDSTMT = 24;
  public int JJTIFSTMT = 25;
  public int JJTWHILESTMT = 26;
  public int JJTDOSTMT = 27;
  public int JJTFORSTMT = 28;
  public int JJTTRYSTMT = 29;
  public int JJTHANDLECLAUSE = 30;
  public int JJTSUITE = 31;
  public int JJTWITHSTMT = 32;
  public int JJTWITHITEM = 33;
  public int JJTTEST = 34;
  public int JJTORTEST = 35;
  public int JJTXORTEST = 36;
  public int JJTANDTEST = 37;
  public int JJTNOTTEST = 38;
  public int JJTCOMPARISON = 39;
  public int JJTCOMPOP = 40;
  public int JJTEXPR = 41;
  public int JJTXOREXPR = 42;
  public int JJTANDEXPR = 43;
  public int JJTSHIFTEXPR = 44;
  public int JJTARITHEXPR = 45;
  public int JJTTERM = 46;
  public int JJTFACTOR = 47;
  public int JJTPOWER = 48;
  public int JJTATOMEXPR = 49;
  public int JJTATOM = 50;
  public int JJTNAME = 51;
  public int JJTNUMBER = 52;
  public int JJTTRUE = 53;
  public int JJTFALSE = 54;
  public int JJTARGS = 55;
  public int JJTSTRING = 56;
  public int JJTTESTLISTCOMP = 57;
  public int JJTTRAILER = 58;
  public int JJTSUBSCRIPTLIST = 59;
  public int JJTSUBSCRIPT = 60;
  public int JJTARGLIST = 61;
  public int JJTARGUMENT = 62;
  public int JJTCOMPITER = 63;
  public int JJTCOMPFOR = 64;
  public int JJTCOMPIF = 65;
  public int JJTSLICEOP = 66;
  public int JJTEXPRLIST = 67;
  public int JJTSTAREXPR = 68;
  public int JJTTESTLIST = 69;
  public int JJTFUNCDEF = 70;
  public int JJTCLASSDEF = 71;
  public int JJTMODIFIER = 72;
  public int JJTCLASSNAME = 73;
  public int JJTINTERFACENAME = 74;
  public int JJTCLASSSUITE = 75;
  public int JJTCLASSSTMT = 76;
  public int JJTMETHODDEF = 77;
  public int JJTCONSTRUCTORDEF = 78;
  public int JJTVARDEF = 79;
  public int JJTINTERFACEDEF = 80;
  public int JJTPARAMETERS = 81;
  public int JJTTYPEDARGLIST = 82;
  public int JJTTFPDEF = 83;
  public int JJTLAMBDEF = 84;
  public int JJTLAMBDEFNOCOND = 85;
  public int JJTVARARGLIST = 86;
  public int JJTTESTNOCOND = 87;
  public int JJTERROR_PRINTMESSAGE = 88;


  public String[] jjtNodeName = {
    "Input",
    "void",
    "SimpleStmt",
    "ExprStmt",
    "Annassign",
    "TestlistStarExpr",
    "Augassign",
    "FlowStmt",
    "BreakStmt",
    "ContinueStmt",
    "ReturnStmt",
    "YieldStmt",
    "YieldExpr",
    "YieldArg",
    "RaiseStmt",
    "ImportStmt",
    "ImportName",
    "ImportFrom",
    "ImportAsName",
    "DottedAsName",
    "ImportAsNames",
    "DottedAsNames",
    "DottedName",
    "AssertStmt",
    "CompoundStmt",
    "IfStmt",
    "WhileStmt",
    "DoStmt",
    "ForStmt",
    "TryStmt",
    "HandleClause",
    "Suite",
    "WithStmt",
    "WithItem",
    "Test",
    "OrTest",
    "XorTest",
    "AndTest",
    "NotTest",
    "Comparison",
    "CompOp",
    "Expr",
    "XorExpr",
    "AndExpr",
    "ShiftExpr",
    "ArithExpr",
    "Term",
    "Factor",
    "Power",
    "AtomExpr",
    "Atom",
    "Name",
    "Number",
    "True",
    "False",
    "Args",
    "String",
    "TestlistComp",
    "Trailer",
    "Subscriptlist",
    "Subscript",
    "Arglist",
    "Argument",
    "CompIter",
    "CompFor",
    "CompIf",
    "SliceOp",
    "Exprlist",
    "StarExpr",
    "Testlist",
    "FuncDef",
    "ClassDef",
    "Modifier",
    "ClassName",
    "InterfaceName",
    "ClassSuite",
    "ClassStmt",
    "MethodDef",
    "ConstructorDef",
    "VarDef",
    "InterfaceDef",
    "Parameters",
    "TypeDArglist",
    "TfpDef",
    "LambDef",
    "LambDefNocond",
    "VarArglist",
    "TestNocond",
    "error_printmessage",
  };
}
/* JavaCC - OriginalChecksum=036d928805a5f1f12cc9aaffefb7dbef (do not edit this line) */
