/* Generated By:JJTree&JavaCC: Do not edit this line. GrammarConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 3;
  /** RegularExpression Id. */
  int PLUS = 4;
  /** RegularExpression Id. */
  int MINUS = 5;
  /** RegularExpression Id. */
  int MULTIPLY = 6;
  /** RegularExpression Id. */
  int DIVIDE = 7;
  /** RegularExpression Id. */
  int ASSIGN = 8;
  /** RegularExpression Id. */
  int MOD = 9;
  /** RegularExpression Id. */
  int TILDE = 10;
  /** RegularExpression Id. */
  int POWER = 11;
  /** RegularExpression Id. */
  int DIVIDEINT = 12;
  /** RegularExpression Id. */
  int SHIFTLEFT = 13;
  /** RegularExpression Id. */
  int SHIFTRIGHT = 14;
  /** RegularExpression Id. */
  int GREATER = 15;
  /** RegularExpression Id. */
  int LESS = 16;
  /** RegularExpression Id. */
  int EQUALS = 17;
  /** RegularExpression Id. */
  int GREATEREQ = 18;
  /** RegularExpression Id. */
  int LESSEQ = 19;
  /** RegularExpression Id. */
  int NOTEQ = 20;
  /** RegularExpression Id. */
  int IN = 21;
  /** RegularExpression Id. */
  int NOT = 22;
  /** RegularExpression Id. */
  int IS = 23;
  /** RegularExpression Id. */
  int PLUSEQ = 24;
  /** RegularExpression Id. */
  int MINUSEQ = 25;
  /** RegularExpression Id. */
  int MULTIPLYEQ = 26;
  /** RegularExpression Id. */
  int DIVIDEEQ = 27;
  /** RegularExpression Id. */
  int MODEQ = 28;
  /** RegularExpression Id. */
  int ANDEQ = 29;
  /** RegularExpression Id. */
  int OREQ = 30;
  /** RegularExpression Id. */
  int XOREQ = 31;
  /** RegularExpression Id. */
  int SHIFTLEFTEQ = 32;
  /** RegularExpression Id. */
  int SHIFTRIGHTEQ = 33;
  /** RegularExpression Id. */
  int POWEREQ = 34;
  /** RegularExpression Id. */
  int DIVIDEINTEQ = 35;
  /** RegularExpression Id. */
  int COLON = 36;
  /** RegularExpression Id. */
  int SEMICOLON = 37;
  /** RegularExpression Id. */
  int ELLIPSES = 38;
  /** RegularExpression Id. */
  int DOT = 39;
  /** RegularExpression Id. */
  int COMMA = 40;
  /** RegularExpression Id. */
  int OPENBRACE = 41;
  /** RegularExpression Id. */
  int CLOSEBRACE = 42;
  /** RegularExpression Id. */
  int LAMBDA = 43;
  /** RegularExpression Id. */
  int ABSTRACT = 44;
  /** RegularExpression Id. */
  int AND = 45;
  /** RegularExpression Id. */
  int ARGS = 46;
  /** RegularExpression Id. */
  int AS = 47;
  /** RegularExpression Id. */
  int ASSERT = 48;
  /** RegularExpression Id. */
  int BREAK = 49;
  /** RegularExpression Id. */
  int CLASS = 50;
  /** RegularExpression Id. */
  int CONTINUE = 51;
  /** RegularExpression Id. */
  int DEFINE = 52;
  /** RegularExpression Id. */
  int DO = 53;
  /** RegularExpression Id. */
  int ELSE = 54;
  /** RegularExpression Id. */
  int ELSEIF = 55;
  /** RegularExpression Id. */
  int FALSE = 56;
  /** RegularExpression Id. */
  int FINALLY = 57;
  /** RegularExpression Id. */
  int FOLLOWS = 58;
  /** RegularExpression Id. */
  int FOR = 59;
  /** RegularExpression Id. */
  int FROM = 60;
  /** RegularExpression Id. */
  int HANDLE = 61;
  /** RegularExpression Id. */
  int IF = 62;
  /** RegularExpression Id. */
  int IMPORT = 63;
  /** RegularExpression Id. */
  int INTERFACE = 64;
  /** RegularExpression Id. */
  int OR = 65;
  /** RegularExpression Id. */
  int PRIVATE = 66;
  /** RegularExpression Id. */
  int PROTECTED = 67;
  /** RegularExpression Id. */
  int PUBLIC = 68;
  /** RegularExpression Id. */
  int RAISE = 69;
  /** RegularExpression Id. */
  int RETURN = 70;
  /** RegularExpression Id. */
  int STATIC = 71;
  /** RegularExpression Id. */
  int THIS = 72;
  /** RegularExpression Id. */
  int TRUE = 73;
  /** RegularExpression Id. */
  int TRY = 74;
  /** RegularExpression Id. */
  int WHILE = 75;
  /** RegularExpression Id. */
  int WITH = 76;
  /** RegularExpression Id. */
  int XOR = 77;
  /** RegularExpression Id. */
  int YIELD = 78;
  /** RegularExpression Id. */
  int NAME = 90;
  /** RegularExpression Id. */
  int NEWLINE = 91;
  /** RegularExpression Id. */
  int STRING = 92;
  /** RegularExpression Id. */
  int NUMBER = 93;
  /** RegularExpression Id. */
  int INT = 94;
  /** RegularExpression Id. */
  int FLOAT = 95;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\" \"",
    "<SINGLE_LINE_COMMENT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"%\"",
    "<TILDE>",
    "\"**\"",
    "\"//\"",
    "\"<<\"",
    "\">>\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"in\"",
    "\"not\"",
    "\"is\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"**=\"",
    "\"//=\"",
    "\":\"",
    "\";\"",
    "\"...\"",
    "\".\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"=>\"",
    "\"abstract\"",
    "\"and\"",
    "\"args\"",
    "\"as\"",
    "\"assert\"",
    "\"break\"",
    "\"class\"",
    "\"continue\"",
    "\"define\"",
    "\"do\"",
    "\"else\"",
    "\"elseif\"",
    "\"false\"",
    "\"finally\"",
    "\"follows\"",
    "\"for\"",
    "\"from\"",
    "\"handle\"",
    "\"if\"",
    "\"import\"",
    "\"interface\"",
    "\"or\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"raise\"",
    "\"return\"",
    "\"static\"",
    "\"this\"",
    "\"true\"",
    "\"try\"",
    "\"while\"",
    "\"with\"",
    "\"xor\"",
    "\"yield\"",
    "\"~~~\"",
    "\"~~~\"",
    "<token of kind 81>",
    "\"(\"",
    "\")\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"[\"",
    "\"]\"",
    "\"->\"",
    "<NAME>",
    "<NEWLINE>",
    "<STRING>",
    "<NUMBER>",
    "<INT>",
    "<FLOAT>",
  };

}
