/* Generated By:JavaCC: Do not edit this line. GrammarTreeConstants.java Version 5.0 */
public interface GrammarTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTSTMT = 1;
  public int JJTSIMPLESTMT = 2;
  public int JJTSMALLSTMT = 3;
  public int JJTEXPRSTMT = 4;
  public int JJTANNASSIGN = 5;
  public int JJTTESTLISTSTAREXPR = 6;
  public int JJTAUGASSIGN = 7;
  public int JJTFLOWSTMT = 8;
  public int JJTBREAKSTMT = 9;
  public int JJTCONTINUESTMT = 10;
  public int JJTRETURNSTMT = 11;
  public int JJTYIELDSTMT = 12;
  public int JJTYIELDEXPR = 13;
  public int JJTYIELDARG = 14;
  public int JJTRAISESTMT = 15;
  public int JJTIMPORTSTMT = 16;
  public int JJTIMPORTNAME = 17;
  public int JJTIMPORTFROM = 18;
  public int JJTIMPORTASNAME = 19;
  public int JJTDOTTEDASNAME = 20;
  public int JJTIMPORTASNAMES = 21;
  public int JJTDOTTEDASNAMES = 22;
  public int JJTDOTTEDNAME = 23;
  public int JJTASSERTSTMT = 24;
  public int JJTCOMPOUNDSTMT = 25;
  public int JJTIFSTMT = 26;
  public int JJTWHILESTMT = 27;
  public int JJTDOSTMT = 28;
  public int JJTFORSTMT = 29;
  public int JJTTRYSTMT = 30;
  public int JJTHANDLECLAUSE = 31;
  public int JJTSUITE = 32;
  public int JJTWITHSTMT = 33;
  public int JJTWITHITEM = 34;
  public int JJTTEST = 35;
  public int JJTORTEST = 36;
  public int JJTXORTEST = 37;
  public int JJTANDTEST = 38;
  public int JJTNOTTEST = 39;
  public int JJTCOMPARISON = 40;
  public int JJTCOMPOP = 41;
  public int JJTEXPR = 42;
  public int JJTXOREXPR = 43;
  public int JJTANDEXPR = 44;
  public int JJTSHIFTEXPR = 45;
  public int JJTARITHEXPR = 46;
  public int JJTTERM = 47;
  public int JJTFACTOR = 48;
  public int JJTPOWER = 49;
  public int JJTATOMEXPR = 50;
  public int JJTATOM = 51;
  public int JJTTESTLISTCOMP = 52;
  public int JJTTRAILER = 53;
  public int JJTSUBSCRIPTLIST = 54;
  public int JJTSUBSCRIPT = 55;
  public int JJTARGLIST = 56;
  public int JJTARGUMENT = 57;
  public int JJTCOMPITER = 58;
  public int JJTCOMPFOR = 59;
  public int JJTCOMPIF = 60;
  public int JJTSLICEOP = 61;
  public int JJTEXPRLIST = 62;
  public int JJTSTAREXPR = 63;
  public int JJTTESTLIST = 64;
  public int JJTFUNCDEF = 65;
  public int JJTCLASSDEF = 66;
  public int JJTMODIFIER = 67;
  public int JJTCLASSNAME = 68;
  public int JJTINTERFACENAME = 69;
  public int JJTCLASSSUITE = 70;
  public int JJTCLASSSTMT = 71;
  public int JJTMETHODDEF = 72;
  public int JJTCONSTRUCTORDEF = 73;
  public int JJTVARDEF = 74;
  public int JJTINTERFACEDEF = 75;
  public int JJTPARAMETERS = 76;
  public int JJTTYPEDARGLIST = 77;
  public int JJTTFPDEF = 78;
  public int JJTLAMBDEF = 79;
  public int JJTLAMBDEFNOCOND = 80;
  public int JJTVARARGLIST = 81;
  public int JJTTESTNOCOND = 82;
  public int JJTERROR_IFSTMT = 83;
  public int JJTERROR_WHILESTMT = 84;
  public int JJTERROR_DOSTMT = 85;
  public int JJTERROR_FORSTMT1 = 86;
  public int JJTERROR_FORSTMT2 = 87;
  public int JJTERROR_SUITE = 88;
  public int JJTERROR_FUNCDEF = 89;
  public int JJTERROR_CLASSDEF = 90;
  public int JJTERROR_CLASSSUITE = 91;
  public int JJTERROR_METHODDEF = 92;
  public int JJTERROR_PRINTMESSAGE = 93;


  public String[] jjtNodeName = {
    "Input",
    "Stmt",
    "SimpleStmt",
    "SmallStmt",
    "ExprStmt",
    "Annassign",
    "TestlistStarExpr",
    "Augassign",
    "FlowStmt",
    "BreakStmt",
    "ContinueStmt",
    "ReturnStmt",
    "YieldStmt",
    "YieldExpr",
    "YieldArg",
    "RaiseStmt",
    "ImportStmt",
    "ImportName",
    "ImportFrom",
    "ImportAsName",
    "DottedAsName",
    "ImportAsNames",
    "DottedAsNames",
    "DottedName",
    "AssertStmt",
    "CompoundStmt",
    "IfStmt",
    "WhileStmt",
    "DoStmt",
    "ForStmt",
    "TryStmt",
    "HandleClause",
    "Suite",
    "WithStmt",
    "WithItem",
    "Test",
    "OrTest",
    "XorTest",
    "AndTest",
    "NotTest",
    "Comparison",
    "CompOp",
    "Expr",
    "XorExpr",
    "AndExpr",
    "ShiftExpr",
    "ArithExpr",
    "Term",
    "Factor",
    "Power",
    "AtomExpr",
    "Atom",
    "TestlistComp",
    "Trailer",
    "Subscriptlist",
    "Subscript",
    "Arglist",
    "Argument",
    "CompIter",
    "CompFor",
    "CompIf",
    "SliceOp",
    "Exprlist",
    "StarExpr",
    "Testlist",
    "FuncDef",
    "ClassDef",
    "Modifier",
    "ClassName",
    "InterfaceName",
    "ClassSuite",
    "ClassStmt",
    "MethodDef",
    "ConstructorDef",
    "VarDef",
    "InterfaceDef",
    "Parameters",
    "TypeDArglist",
    "TfpDef",
    "LambDef",
    "LambDefNocond",
    "VarArglist",
    "TestNocond",
    "ERROR_IfStmt",
    "ERROR_WhileStmt",
    "ERROR_DoStmt",
    "ERROR_ForStmt1",
    "ERROR_ForStmt2",
    "ERROR_Suite",
    "ERROR_FuncDef",
    "ERROR_ClassDef",
    "ERROR_ClassSuite",
    "ERROR_MethodDef",
    "error_printmessage",
  };
}
/* JavaCC - OriginalChecksum=62f610aefd60a3c2833488c6c5549ced (do not edit this line) */
